<?php
return [
  [
    'title' => '后台管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'admin',
    'url' => 'admin',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 1,
    'childs' => [
      [
        'title' => '首页管理',
        'icon' => 'aicon ai-shouyeshouye',
        'module' => 'admin',
        'url' => 'admin/index/default',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '轮播广告',
            'icon' => 'aicon ai-shuaxin2',
            'module' => 'admin',
            'url' => 'admin/banner/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '产品分类',
            'icon' => 'typcn typcn-th-small',
            'module' => 'admin',
            'url' => 'admin/category/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '全部产品',
            'icon' => 'aicon ai-systemmenu',
            'module' => 'admin',
            'url' => 'admin/product/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '实训室列表',
            'icon' => 'typcn typcn-pin-outline',
            'module' => 'admin',
            'url' => 'admin/laboratory/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '实训室系列视频',
            'icon' => 'typcn typcn-video',
            'module' => 'admin',
            'url' => 'admin/laboratoryVideo/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
